apiVersion: v1
kind: Pod
metadata:
  name: five-counter-pod
  labels:
    app: webapp
spec:
  containers:
  - name: counter-1
    image: busybox
    args: [/bin/sh, -c,
          'i=1; while [ $i -le 4 ]; do echo "From Container-1 - $i: Hello World"; i=$((i+1)); sleep 3; done']
  - name: counter-2
    image: busybox
    args: [/bin/sh, -c,
          'i=5; while [ $i -le 8 ]; do echo "From Container-2 - $i: Hello World"; i=$((i+1)); sleep 3; done']
  - name: counter-3
    image: busybox
    args: [/bin/sh, -c,
          'i=9; while [ $i -le 12 ]; do echo "From Container-3 - $i: Hello World"; i=$((i+1)); sleep 3; done']
  - name: counter-4
    image: busybox
    args: [/bin/sh, -c,
          'i=13; while [ $i -le 16 ]; do echo "From Container-4- $i: Hello World"; i=$((i+1)); sleep 3; done']
  - name: counter-5
    image: busybox
    args: [/bin/sh, -c,
          'i=17; while [ $i -le 20 ]; do echo "From Container-5 - $i: Hello World"; i=$((i+1)); sleep 3; done']
 
 
 
  restartPolicy: OnFailure
 
