apiVersion: v1
kind: Pod
metadata:
  name: nginx-hostpath
spec:
  containers:
     - image: nginx
       name: nginx-container
       volumeMounts:
       - mountPath: /test-mnt
         name: test-vol
  volumes:
  - name: test-vol
    hostPath:
      path: /test-vol
