apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-pvc
spec:
  storageClassName: fast-sc  #Using Storage Class created in step-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
